### Ejemplo 1 con KMeans

In [1]:
#Importamos el dataset que vamos a utilizar
from sklearn.datasets import load_iris
data = load_iris()

In [3]:
X = data['data'] #Es la información que tenemos de cada columna (salvo la etiqueta)

In [4]:
from sklearn.cluster import KMeans

In [6]:
kmeans = KMeans(n_clusters = 3) #Sabemos que tenemos tres clases por el dataset, normalmente no lo tendremos
kmeans.fit(X) #Le pasamos la información

KMeans(n_clusters=3)

In [7]:
kmeans.labels_ #Las etiquetas las pone aleatoriamente, es decir en este caso de ejecución para concordar
#Con nuestras labels le a puesto a las 0 y 1 y viceversa, pero lo que importa es la agrupacion

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 2, 0, 0, 2, 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 0, 0, 2, 2, 2, 2,
       2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0])

In [8]:
kmeans.cluster_centers_

array([[5.9016129 , 2.7483871 , 4.39354839, 1.43387097],
       [5.006     , 3.428     , 1.462     , 0.246     ],
       [6.85      , 3.07368421, 5.74210526, 2.07105263]])

### Ejemplo 2 con DBSCAN

In [10]:
Y = data['data']

In [11]:
from sklearn.cluster import DBSCAN

In [138]:
dbscan = DBSCAN(eps=0.8, min_samples=2)
dbscan.fit(Y)

DBSCAN(eps=0.8, min_samples=2)

In [139]:
dbscan.labels_

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [135]:
dbscan = DBSCAN(eps=0.6, min_samples=5)
dbscan.fit(Y)
dbscan.labels_

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  1,
        1,  1,  1,  1,  1,  1, -1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1, -1,  1,  1,  1,
        1,  1,  1,  1, -1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1, -1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
      dtype=int64)

In [142]:
#Para intentar encontrar estos hiperparametros podemos usuar
import numpy as np
for eps in np.arange(0.1,1,0.1):
    for min_samples in range (2,20):
        dbscan2 = DBSCAN(eps=eps, min_samples=min_samples)
        dbscan2.fit(Y)
        print('------')
        print(eps)
        print(min_samples)
        print(len(set(dbscan2.labels_)))
        print(list(dbscan2.labels_).count(-1))

------
0.1
2
5
142
------
0.1
3
1
150
------
0.1
4
1
150
------
0.1
5
1
150
------
0.1
6
1
150
------
0.1
7
1
150
------
0.1
8
1
150
------
0.1
9
1
150
------
0.1
10
1
150
------
0.1
11
1
150
------
0.1
12
1
150
------
0.1
13
1
150
------
0.1
14
1
150
------
0.1
15
1
150
------
0.1
16
1
150
------
0.1
17
1
150
------
0.1
18
1
150
------
0.1
19
1
150
------
0.2
2
20
89
------
0.2
3
7
115
------
0.2
4
4
128
------
0.2
5
3
133
------
0.2
6
3
135
------
0.2
7
2
141
------
0.2
8
2
142
------
0.2
9
1
150
------
0.2
10
1
150
------
0.2
11
1
150
------
0.2
12
1
150
------
0.2
13
1
150
------
0.2
14
1
150
------
0.2
15
1
150
------
0.2
16
1
150
------
0.2
17
1
150
------
0.2
18
1
150
------
0.2
19
1
150
------
0.30000000000000004
2
22
43
------
0.30000000000000004
3
10
67
------
0.30000000000000004
4
7
81
------
0.30000000000000004
5
4
96
------
0.30000000000000004
6
3
106
------
0.30000000000000004
7
3
108
------
0.30000000000000004
8
2
117
------
0.30000000000000004
9
2
118
------
0.300000000