In [1]:
import numpy as np
print(np.__version__)

1.20.1


Indicar qué código genera una matriz de 3x3 con todos los valores a True

In [7]:
array = np.ones((3,3), dtype=bool)
#np.full((3, 3), True, dtype=bool)
#np.array([True] * 9).reshape(3, 3)
print(array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


Dado el array:
arr = np.arange(10)
Indicar qué código reemplaza todos los números impares sin modificar el array original.

In [15]:
arr = np.arange(10)
arr2 = np.where(arr % 2 == 1, -1, arr)
print(arr)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


Dados los arrays:

a = np.ones((3, 3))
b = np.zeros((3, 3))
Indicar cuál de los siguientes códigos los apila verticalmente:

In [22]:
a = np.ones((3, 3))
b = np.zeros((3, 3))
#apilados = np.vstack([a, b])
#apilados = np.concatenate([a, b], axis=0)
apilados = np.r_[a, b]
print(apilados)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Dados los arrays:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
Indicar el código que obtiene las posiciones en las que sus valores coinciden:
array([1,3,5,7])

In [31]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
#comunes = np.intersect1d(a,b)
#comunes = np.array(list(set(a).intersection(set(b))))
comunes = np.unique([x for x in a if x in b])
comunes

array([2, 4])

Dados los arrays:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
Indicar el código que obtiene las posiciones en las que sus valores coinciden:
array([1,3,5,7])

In [36]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
#posiciones = np.where(a == b)[0]
posiciones = np.array([i for i, x in enumerate(a == b) if x])
posiciones

array([1, 3, 5, 7])

Dado el siguiente  array:

a = np.array([2, 6, 1, 9, 10, 3, 27])
Indicar qué codigo obtiene los valores entre 5 y 10:
array([6, 9, 10])

In [41]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
#a[(a >= 5) & (a <= 10)]
a[np.where((a >= 5) & (a <= 10))]

array([[ 6,  9, 10]])

¿Son equivalentes las siguientes expresiones?

np.isnan(a).any()
np.any(a==np.nan)

In [43]:
print(np.isnan(a).any())
print(np.any(a==np.nan))

False
False


La siguiente instrucción:

np.where(a < 10, 10, np.where(a > 30, 30, a))
¿Actualiza el array a cambiando los valores mayores que 30 por 30 y los menores de 10 po 10?

In [49]:
a = np.arange(50)
print(a)

print(np.sort(a)[:-5:-1])

a[~np.isnan(a)]


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[49 48 47 46]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [52]:
a = np.array([np.nan,  1,  2,  3, np.nan,  4,  5, np.nan,  7,  8,  9, np.nan])
a[~np.isnan(a)]


array([1., 2., 3., 4., 5., 7., 8., 9.])