# Ejercicios de introducción a Numpy 

In [2]:
import numpy as np
print(np.__version__)

1.20.1


1.- Extrae todos los número impares de un array:
```python
 In: array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Out: array([1, 3, 5, 7, 9])
```

In [8]:
array = np.arange(10)
array[array % 2 != 0]

array([1, 3, 5, 7, 9])

2.- Reemplaza los números impares de un array con valores fijos:
```python
 In: array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Out: array([0, -1, 2, -1, 4, -1, 6, -1, 8, -1])
```

In [11]:
array = np.arange(10)
array[array % 2 != 0] = -1 #Se aplica a todo el array y modifica el original
array

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

3.- Reemplaza los números impares de un array con valores fijos sin afectar al array original:
```python
 In: array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Out: array([0, -1, 2, -1, 4, -1, 6, -1, 8, -1])
```

In [ ]:
array = np.arange(10)
np.where(array % 2 != 0)
array

4.- Convertir un array de 1D en un array de 2D:  
```python
 In: array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Out: array([[0, 1, 2, 3, 4],
            [5, 6, 7, 8, 9]])
```

In [12]:
array = np.arange(10)
np.reshape(array, (2,-1)) #Significa el numero de columnas que sea necesaria -1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

5.- Apilar verticalmente dos arrays:  
```python
 In: array([[0, 1, 2, 3, 4],
            [5, 6, 7, 8, 9]]),
     array([[1, 1, 1, 1, 1]
            [1, 1, 1, 1, 1]])
Out: array([[0, 1, 2, 3, 4],
            [5, 6, 7, 8, 9],
            [1, 1, 1, 1, 1],
            [1, 1, 1, 1, 1]])
```

In [15]:
a = np.array([[0, 1, 2, 3, 4],
            [5, 6, 7, 8, 9]])
b = np.array([[1, 1, 1, 1, 1],
            [1, 1, 1, 1, 1]])
np.concatenate([a,b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

6.- Apilar horizontalmente dos arrays:  
```python
 In: array([[0, 1, 2, 3, 4],
            [5, 6, 7, 8, 9]]),
     array([[1, 1, 1, 1, 1]
            [1, 1, 1, 1, 1]])
Out: array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
            [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
```

In [24]:
array1 = np.array([[0, 1, 2, 3, 4],
            [5, 6, 7, 8, 9]])
array2 = np.array([[1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1]])
#np.concatenate([a,b], axis=1)
array3 = np.column_stack((array1,array2))
print(array3)


[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


7.- Crea el siguiente patrón sin codificación. Utilice solo las funciones numpy y la siguiente matriz de entrada: 
```python
 In: arr1 = np.array([1,2,3])
Out: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [19]:
arr1 = np.array([1,2,3])
np.r_[np.repeat(arr1, 3), np.tile(arr1, 3)] #r_ afecta a las row


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

8.- Obtener las posiciones de los elementos que coinciden en dos arrays:  
```python
 In: array([1,2,3,2,3,4,3,4,5,6]),
     array([7,2,10,2,7,4,9,4,9,8])
Out: array([1, 3, 5, 7])
```

In [20]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])


[2 4]


9.- Obtener todos los items entre 5 y 10 del siguiente array:  
```python
 In: array([2, 6, 1, 9, 10, 3, 27])
Out: array([6, 9, 10]) 
```

In [43]:
array = np.array([2, 6, 1, 9, 10, 3, 27])
index_array2 = np.where((array >= 5) & (array <= 10)) #Devuelve las posiciones
print(array[index_array2])

[ 6  9 10]


10.- Intercambia dos columnas de un array (columnas 0 y 1):  
```python
 In: array([[0, 1, 2],
            [3, 4, 5],
            [6, 7, 8]])
Out: array([[1, 0, 2],
            [4, 3, 5],
            [7, 6, 8]])
```

In [21]:
arr1 = np.arange(9).reshape(3,3)
arr1[:,[1,0,2]]
arr1.take([1,0,2], axis=1)

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

11.- Intercambia dos filas de un array (filas 0 y 1):  
```python
 In: array([[0, 1, 2],
            [3, 4, 5],
            [6, 7, 8]])
Out: array([[3, 4, 5],
            [0, 1, 2],
            [6, 7, 8]])
```

In [22]:
arr1 = np.arange(9).reshape(3,3)
arr1[:,[1,0,2]]
arr1.take([1,0,2], axis=0)

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

12.- Invierte todas las filas de un array 2D:  
```python
 In: array([[0, 1, 2],
            [3, 4, 5],
            [6, 7, 8]])
Out: array([[2, 1, 0],
            [5, 4, 3],
            [8, 7, 6]])
```

In [45]:
array = np.array([[0, 1, 2],
[3, 4, 5],
[6, 7, 8]])
array2 = np.flip(array, axis=1) #array[::-1]
print(array2)

[[2 1 0]
 [5 4 3]
 [8 7 6]]


13.- Invierte todas las columnas de un array 2D:  
```python
 In: array([[0, 1, 2],
            [3, 4, 5],
            [6, 7, 8]])
Out: array([[2, 1, 0],
            [5, 4, 3],
            [8, 7, 6]])
```

In [48]:
array = np.array([[0, 1, 2],
[3, 4, 5],
[6, 7, 8]])
array2 = np.flip(array, axis=0) #array[:,::-1]
print(array2)

[[6 7 8]
 [3 4 5]
 [0 1 2]]


14.- Crear un array 2D con *shape* 5x3 que contenga números decimales aleatorios entre 5 y 10:  
```python
Out: [[ 8.50061025  9.10531502  6.85867783]
      [ 9.76262069  9.87717411  7.13466701]
      [ 7.48966403  8.33409158  6.16808631]
      [ 7.75010551  9.94535696  5.27373226]
      [ 8.0850361   5.56165518  7.31244004]]
```

In [60]:
array = np.random.uniform(5,10, size=(5,3))
print(array)

[[6.3530177  6.69384286 6.04183459]
 [5.20947431 7.37566146 8.65256848]
 [9.58233702 8.21205913 5.68989967]
 [8.22992433 7.9789167  7.08005734]
 [5.40901533 9.39848508 5.58471468]]


15.- indicar el número de elementos nulos, igual a `np.nan`, y su posición:  
```python
 In: array([np.nan,  1,  2,  3, np.nan,  4,  5, np.nan,  7,  8,  9, np.nan])
Out: Hay 4 valores nulos en las posiciones [0, 4, 7, 11]
```

In [30]:
nulos = np.array([np.nan,  1,  2,  3, np.nan,  4,  5, np.nan,  7,  8,  9, np.nan])
nan = np.isnan(nulos).sum()
posiciones = np.where(np.isnan(nulos))
print(nan, posiciones)

4 (array([ 0,  4,  7, 11], dtype=int64),)


16.- Escribir un código que devuelva los valores únicos de un array y su número de apariciones:  
```python
 In: array([1, 1, 2, 3, 3, 4, 5, 5, 7, 8, 9, 9])
Out: (array([1, 2, 3, 4, 5, 7, 8, 9]), array([2, 1, 2, 1, 2, 1, 1, 2]))
```

In [32]:
array = np.array([1, 1, 2, 3, 3, 4, 5, 5, 7, 8, 9, 9])
np.unique(array, return_counts=True)

(array([1, 2, 3, 4, 5, 7, 8, 9]), array([2, 1, 2, 1, 2, 1, 1, 2], dtype=int64))

17.- Crear una matriz de 5x5 como la siguiente:  
```python
Out: [[1. 1. 1. 1. 1.]
      [1. 0. 0. 0. 1.]
      [1. 0. 0. 0. 1.]
      [1. 0. 0. 0. 1.]
      [1. 1. 1. 1. 1.]]
```

In [51]:
arr1 = np.zeros((5,5))
arr1[[0,-1],:] = 1
arr1[:, [0,-1]] = 1
arr1

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
arr1 = np.ones((5,5))
arr1[1:-1, 1:-1] = 0
arr1

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

18.- Crear una matriz de 5x5 como la siguiente:  
```python
Out: [[1 0 0 0 0]
      [0 2 0 0 0]
      [0 0 3 0 0]
      [0 0 0 4 0]
      [0 0 0 0 5]]
```

In [55]:
arr1 = np.zeros((5,5))
np.diag(range(1,6))
arr1

IndexError: index 5 is out of bounds for axis 0 with size 5

19.- Crear una matriz de 4x4 como la siguiente:  
```python
Out: [[0. 1. 0. 1.]
      [1. 0. 1. 0.]
      [0. 1. 0. 1.]
      [1. 0. 1. 0.]]
```

In [58]:
arr1 = np.zeros((4,4))
arr1[::2,1::2] = 1
arr1[1::2,::2] = 1
arr1

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

20.- Proporcionar la suma de todos los valores de una matriz y de sus filas y columnas:
```python
 In: array([[0,1],[2,3]])
Out: Suma total 6, por filas [2, 4] por columnas [1, 5]
```

21.- Crear un programa que dada una matriz añada un borde de 0's rodeándola: 
```python
 In: array([[ 1.  2.  3.]                                                          
            [ 4.  5.  6.]                                                          
            [ 7.  8.  9.]])
Out: array([[ 0.  0.  0.  0.  0.]                                                  
            [ 0.  1.  2.  3.  0.]                                                  
            [ 0.  4.  5.  6.  0.]                                                  
            [ 0.  7.  8.  9.  0.]                                                  
            [ 0.  0.  0.  0.  0.]])
```

22.- Crear una matriz de 3x5 rellena de '2': 
```python
Out: array([[2 2 2 2 2]
            [2 2 2 2 2]
            [2 2 2 2 2]])
```

23.- Crear una matriz igual que una dada pero rellena de otro valor: 
```python
 In: array([0, 1, 2, 3])
Out: array([10, 10, 10, 10])
```

24.- Crear una matriz de 8x8 con el siguiente contenido:
```python
Out: [[ 0  1  0  2  0  3  0  4]
      [16  0 15  0 14  0 13  0]
      [ 0  5  0  6  0  7  0  8]
      [12  0 11  0 10  0  9  0]
      [ 0  9  0 10  0 11  0 12]
      [ 8  0  7  0  6  0  5  0]
      [ 0 13  0 14  0 15  0 16]
      [ 4  0  3  0  2  0  1  0]]
```

In [71]:
arr1 = np.zeros((8,8))
arra2 = np.arange(16,0,-1).reshape(4,4)
arr1[::2,1::2] = np.arange(1,17).reshape(4,4)
arr1[1::2,::2] = arra2 #filas impares por columnas pares
arr1

array([[ 0.,  1.,  0.,  2.,  0.,  3.,  0.,  4.],
       [16.,  0., 15.,  0., 14.,  0., 13.,  0.],
       [ 0.,  5.,  0.,  6.,  0.,  7.,  0.,  8.],
       [12.,  0., 11.,  0., 10.,  0.,  9.,  0.],
       [ 0.,  9.,  0., 10.,  0., 11.,  0., 12.],
       [ 8.,  0.,  7.,  0.,  6.,  0.,  5.,  0.],
       [ 0., 13.,  0., 14.,  0., 15.,  0., 16.],
       [ 4.,  0.,  3.,  0.,  2.,  0.,  1.,  0.]])

25.- Indicar el numero de bytes de ocupación en memoria de la matriz anterior:
```python
 In: [[0 1 0 1 0 1 0 1]                                                      
      [1 0 1 0 1 0 1 0]                                                      
      [0 1 0 1 0 1 0 1]                                                      
      [1 0 1 0 1 0 1 0]                                                      
      [0 1 0 1 0 1 0 1]                                                      
      [1 0 1 0 1 0 1 0]                                                      
      [0 1 0 1 0 1 0 1]                                                      
      [1 0 1 0 1 0 1 0]]
Out: 512 bytes
```

In [72]:
arr1.nbytes

512

26.- Crear una matriz de 6x5 con 30 números comprendidos entre 2.5. y 6.5, inclusive.
```python
Out: [[2.5       , 2.63793103, 2.77586207, 2.9137931 , 3.05172414],
      [3.18965517, 3.32758621, 3.46551724, 3.60344828, 3.74137931],
      [3.87931034, 4.01724138, 4.15517241, 4.29310345, 4.43103448],
      [4.56896552, 4.70689655, 4.84482759, 4.98275862, 5.12068966],
      [5.25862069, 5.39655172, 5.53448276, 5.67241379, 5.81034483],
      [5.94827586, 6.0862069 , 6.22413793, 6.36206897, 6.5       ]]
```

In [75]:
np.linspace(2.5, 6.5, 30).reshape(6,5)

array([[2.5       , 2.63793103, 2.77586207, 2.9137931 , 3.05172414],
       [3.18965517, 3.32758621, 3.46551724, 3.60344828, 3.74137931],
       [3.87931034, 4.01724138, 4.15517241, 4.29310345, 4.43103448],
       [4.56896552, 4.70689655, 4.84482759, 4.98275862, 5.12068966],
       [5.25862069, 5.39655172, 5.53448276, 5.67241379, 5.81034483],
       [5.94827586, 6.0862069 , 6.22413793, 6.36206897, 6.5       ]])

27.- Obtener el cuarto elemento de la siguiente matriz:
```python
 In: array([[ 2, 4, 6],
            [ 6, 8, 10]])
Out: 6
```

28.- Cambiar la siguiente matriz según el patrón inidcado:
```python
 In: array([[1,2,3]])
Out: array([[1],
            [2],
            [3]])
```

In [77]:
arr1 = np.array([[1,2,3]])
arr1.transpose()

array([[1],
       [2],
       [3]])

29.- Obtener la suma de los números múltiplos de 3 o de 5 contenidos entre el 1 y el 100:
```python
Out: 2318
```

30.- Crear una función que eleve al cuadrado y sume uno a todos los elementos de cualquier matrix:
```python
 In: array([1, 4, 9])
Out: array([ 2,  3, 4])
```

31.a - Importar el dataset `iris` (../data/iris.data) sin proporcionar un tipo por defecto y mostrar las 3 primeras filas recuperadas:
```python
Out: array([[5.1, 3.5, 1.4, 0.2, nan],
            [4.9, 3. , 1.4, 0.2, nan],
            [4.7, 3.2, 1.3, 0.2, nan]])
```

31.b - Importar el dataset `iris_2d` (../data/iris.data) manteniendo intactos los valores de tipo texto (**dtype**=`object`) y mostrar las 3 primeras filas recuperadas:
```python
Out: array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
            [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
            [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']])
```

31.c - Importar el dataset `iris_1d` (../data/iris.data) manteniendo intactos los valores de tipo texto (**dtype**=`None`) y mostrar las 3 primeras filas recuperadas:
```python
Out: array([(5.1, 3.5, 1.4, 0.2, 'Iris-setosa'),
            (4.9, 3. , 1.4, 0.2, 'Iris-setosa'),
            (4.7, 3.2, 1.3, 0.2, 'Iris-setosa')])
```

32.- Recuperar los valores diferentes de columna de texto `species` para los dataset `iris_1d` e `iris_2d` obtenidos en el paso anterior:
```python
Out: ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
```

33.- Recuperar los valores diferentes de columna de texto `species` de los dataset `iris_1d` e `iris_2d` obtenidos en el paso anterior y su número de apariciones:
```python
Out: (array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'], dtype='|S15'),     
      array([50, 50, 50]))
```

34.- Obtener la media, la mediana y la desviación estándar de la columna `sepallength` de los dataset `iris_1d` e `iris_2d`.
```python
Out: 5.843333333333334 5.8 0.8253012917851409
```

35.- Crear una versión normalizada del campo `sepallength` de los dataset `iris_1d` e `iris_2d` cuyos valores estén entre 0 y 1, de modo que el valor mínimo sea 0 y el máximo 1.
```python
Out: array([0.22222222, 0.16666667, 0.11111111, ..., 0.61111111, 0.52777778, 0.44444444])
```

36.- Convertir el array 1D `iris_1d` en un array 2D (`iris_2d`) omitiendo el campo `species`.
```python
Out: array([[5.1, 3.5, 1.4, 0.2],
            [4.9, 3. , 1.4, 0.2],
            [4.7, 3.2, 1.3, 0.2],
            ...,
            [6.5, 3. , 5.2, 2. ],
            [6.2, 3.4, 5.4, 2.3],
            [5.9, 3. , 5.1, 1.8]])
```

37.- Insertar el valor `np.nan` en el primer y último elemento del array `iris_2d` y en 18 posiciones aleatorias adicionales. 
```python
Out: array([[nan, 3.5, 1.4, 0.2],
            [4.9, nan, 1.4, 0.2],
            [4.7, 3.2, 1.3, 0.2],
            ...,
            [6.5, 3. , 5.2, 2. ],
            [6.2, 3.4, 5.4, 2.3],
            [5.9, 3. , 5.1, nan]])
```

38.- Obtener todas las filas del array `iris_2db` que tengan algún valor `np.nan`.
```python
Out: array([[nan, 3.5, 1.4, 0.2],
            [4.9, nan, 1.4, 0.2],
            [nan, nan, 1.4, 0.2],
            ...,
            [nan, 3.2, 5.9, nan],
            [6.7, 3.3, 5.7, nan],
            [5.9, 3. , 5.1, nan]])
```

39.- Encontrar el número y la posición de los elementos `np.nan` de la columna `sepallength` del array `iris_2d`. 
```python
Out: número de posiciones 'nan': 10
     posiciones de los valores 'nan': [  0   8  14 ...  98 107 143]
```

40.- Filtrar las columas del array `iris_2d` cuyo valor de la columna `petallength` sea mayor que 1.5 y cuyo valor de `sepallength` sea menor de 5.0. 
```python
Out: array([[4.8, 3.4, 1.6, 0.2],
            [4.7, 3.2, 1.6, 0.2],
            [4.8, 3.1, 1.6, 0.2],
            [4.9, 2.4, 3.3, 1. ],
            [4.9, 2.5, 4.5, 1.7]])
```

41.- Reemplaza todos los valores `np.nan` del array `iris_2d` con el valor 0.
```python
Out: array([[0. , 3.5, 1.4, 0.2],
            [4.9, 0. , 1.4, 0.2],
            [4.7, 3.2, 1.3, 0.2],
            ...,
            [6.5, 3. , 5.2, 2. ],
            [6.2, 3.4, 5.4, 2.3],
            [5.9, 3. , 5.1, 0. ]])
```

42.- Comprueba que el array `iris_2d` no tiene valores `np.nan`.
```python
Out: False
```

43.- Crear una nueva columna en `iris_2d` cuyo valor sea la multiplicación de las columnas `petallength` y `sepallength`.
```python
Out: array([[ 0.  ,  3.5 ,  1.4 ,  0.2 ,  0.  ],
            [ 4.9 ,  3.  ,  1.4 ,  0.2 ,  6.86],
            [ 4.7 ,  3.2 ,  1.3 ,  0.2 ,  6.11],
            ...,
            [ 6.5 ,  3.  ,  5.2 ,  2.  , 33.8 ],
            [ 6.2 ,  3.4 ,  5.4 ,  2.3 , 33.48],
            [ 5.9 ,  3.  ,  5.1 ,  1.8 , 30.09]])
```

44.- Encontrar el segundo valor más grande de la columna `petallength` para la especie `Iris-setosa`.
```python
Out: 1.7
```

45.- Calcular los percentiles 5 y 95 del campo `sepallength` del dataset `iris`.
```python
Out: array([0. , 7.2])
```

---
<div style="text-align:center">
    [<a href="../numpy.ipynb">Numpy</a>]
    [Ejercicios]
</div>